"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const http = require("node:http");
const path = require("node:path");
const { chromium } = require("playwright");

const root = __dirname;
function server() {
  return http.createServer((request, response) => {
    const pathname = new URL(request.url || "/", "http://127.0.0.1").pathname;
    const file = path.resolve(root, decodeURIComponent(pathname === "/" ? "index.html" : pathname.slice(1)));
    if (!file.startsWith(root + path.sep) || !fs.existsSync(file) || !fs.statSync(file).isFile()) { response.writeHead(404); response.end("not found"); return; }
    response.writeHead(200, { "content-type": file.endsWith(".js") ? "text/javascript" : file.endsWith(".css") ? "text/css" : file.endsWith(".json") ? "application/json" : "text/html", "cache-control": "no-store" });
    fs.createReadStream(file).pipe(response);
  });
}
function listen(instance) { return new Promise((resolve, reject) => { instance.once("error", reject); instance.listen(0, "127.0.0.1", () => resolve(instance.address().port)); }); }

(async () => {
  const instance = server(), port = await listen(instance), browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on("pageerror", (error) => errors.push(error.message));
  try {
    const currentStateResponse = await page.request.get("http://127.0.0.1:" + port + "/current-state.html");
    assert.equal(currentStateResponse.status(), 200);
    assert.match(await currentStateResponse.text(), /Deployment is version-specific/);
    await page.goto("http://127.0.0.1:" + port + "/", { waitUntil: "networkidle" });
    await page.waitForFunction(() => ["ready", "error"].includes(document.querySelector("#geometry-explorer")?.dataset.state), null, { timeout: 20000 });
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-presentation-mode"), "simple");
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-state"), "ready", "Simple mode must begin with a computed slice view");
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-mode"), "slice");
    assert.ok(Number(await page.locator("#geometry-explorer").getAttribute("data-point-count")) > 1000);
    assert.match(await page.locator("[data-simple-geometry-caption]").innerText(), /3D view of a sampled X₀ slice/);
    assert.match(await page.locator("[data-simple-geometry-qualification]").innerText(), /Parameter status: regular/);
    assert.equal(await page.locator("#structural-3d-presentation").isHidden(), true, "Simple mode must not show the structural presentation camera");
    const simpleScale = Number(await page.locator("#geometry-explorer").getAttribute("data-camera-scale"));
    await page.locator("[data-simple-geometry-action='zoom-in']").click();
    await page.waitForFunction((before) => Number(document.querySelector("#geometry-explorer")?.dataset.cameraScale) > before, simpleScale);
    await page.locator("#geometry-explorer canvas").focus();
    const selectedBeforeKey = await page.evaluate(() => window.GeometryExplorer.selectedSliceVertex.id);
    await page.keyboard.press("ArrowRight");
    await page.waitForFunction((before) => window.GeometryExplorer.selectedSliceVertex?.id !== before, selectedBeforeKey);
    const selected = await page.evaluate(() => window.GeometryExplorer.selectedSliceVertex);
    const pointScreen = await page.evaluate((value) => window.GeometryExplorer.sliceVertexScreenPosition(value.branch, value.vertexIndex), selected);
    assert.ok(pointScreen, "A validated surface vertex must have a canvas position");
    const picked = await page.evaluate((point) => window.GeometryExplorer.pickPoint({ clientX: point.x, clientY: point.y }), pointScreen);
    assert.ok(picked && Number.isInteger(picked.vertexIndex), "Canvas picking must resolve a surface triangle to a validated vertex");
    await page.waitForFunction(() => document.querySelector("[data-simple-geometry-selection]")?.textContent.includes("Selected validated X₀ vertex"));
    await page.locator("[data-simple-geometry-action='explore']").click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.mode === "localpatch" && document.querySelector("#geometry-explorer")?.dataset.pointCount === "81");
    assert.match(await page.locator("[data-simple-geometry-caption]").innerText(), /81 paired samples/);
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-geometric-zoom-applied"), "false");
    await page.locator("[data-simple-geometry-action='comparison']").click();
    await page.waitForFunction(() => window.GeometryExplorer.localComparison === "normalized_log_comparison" && document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("[data-simple-geometry-status]")?.textContent.includes("child offsets multiplied by D"));
    assert.match(await page.locator("[data-simple-geometry-status]").innerText(), /child offsets multiplied by D/);
    await page.locator("[data-simple-geometry-action='surface']").click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.mode === "slice");
    await page.evaluate(() => { window.GeometryExplorer.selectedSliceVertex = { branch: 0, vertexIndex: 32 * 47 + 23, id: "slice-b0-i32-j23" }; });
    await page.locator("[data-simple-geometry-action='explore']").click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "refused" && /roots are numerically unresolved/.test(document.querySelector("[data-simple-geometry-caption]")?.textContent || ""));
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-point-count"), "0", "A rejected local chart must not leave child marks.");
    await page.locator("[data-simple-geometry-action='surface']").click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.mode === "slice");
    await page.evaluate(() => { window.GeometryExplorer.selectedSliceVertex = { branch: 0, vertexIndex: 12 * 47 + 8, id: "slice-b0-i12-j8" }; });
    await page.locator("[data-simple-geometry-action='explore']").click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "refused" && /path-dependent/.test(document.querySelector("[data-simple-geometry-caption]")?.textContent || ""));
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-point-count"), "0", "A path-dependent local chart must generate zero child marks.");
    await page.locator("[data-simple-geometry-action='surface']").click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.mode === "slice");
    await page.evaluate(() => {
      window.GeometryExplorer.selectedSliceVertex = { branch: 0, vertexIndex: 32 * 47 + 10, id: "slice-b0-i32-j10" };
      window.GeometryExplorer.pullbackConfig.materialization.maxGeneratedPoints = 80;
    });
    await page.locator("[data-simple-geometry-action='explore']").click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "refused" && /exceeds its materialization cap/.test(document.querySelector("[data-simple-geometry-caption]")?.textContent || ""));
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-required-point-count"), "81");
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-point-count"), "0", "An over-cap local request must generate zero children.");
    await page.evaluate(() => { window.GeometryExplorer.pullbackConfig.materialization.maxGeneratedPoints = 10000; });
    await page.locator("[data-simple-geometry-action='surface']").click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.mode === "slice");
    await page.locator("[data-simple-geometry-action='fermat']").focus(); await page.keyboard.press("Enter");
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.formulaId === "fermat_quintic_cross_section_v1" && document.querySelector("#geometry-explorer")?.dataset.mode === "slice");
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-point-count"), "9375");
    assert.equal(await page.locator("[data-slice-control='xiWindow']").inputValue(), "1.2");
    assert.match(await page.locator("[data-simple-geometry-caption]").innerText(), /25 phase-related patches/);
    assert.match(await page.locator("[data-simple-geometry-boundary]").innerText(), /not the full six-real-dimensional/);
    await page.locator("#geometry-explorer").screenshot({ path: path.join(root, "geometry-explorer-fermat-slice-browser.png") });
    const fermatSourceBefore = await page.evaluate(() => ({ selected: window.GeometryExplorer.selectedSliceVertex.id, sourceIds: window.GeometryExplorer.currentRecord.sourceRecords.map((point) => point.id) }));
    await page.emulateMedia({ reducedMotion: "reduce" });
    await page.locator("[data-simple-geometry-action='explore']").focus(); await page.keyboard.press("Enter");
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.mode === "localpatch" && document.querySelector("#geometry-explorer")?.dataset.pointCount === "81" && window.GeometryExplorer.localComparison === "normalized_log_comparison" && document.querySelector("#geometry-explorer")?.dataset.localComparisonCamera === "central_tangent_fit");
    assert.match(await page.locator("[data-simple-geometry-caption]").innerText(), /After recentering this local log chart/);
    assert.match(await page.locator("[data-local-comparison-evidence]").innerText(), /81 paired samples/);
    const comparisonBefore = await page.evaluate(() => ({ parentIds: window.GeometryExplorer.currentRecord.parentPoints.map((point) => point.id), childIds: window.GeometryExplorer.currentRecord.children.map((point) => point.id), roots: window.GeometryExplorer.currentRecord.rootMultiIndex }));
    const localCameraScale = Number(await page.locator("#geometry-explorer").getAttribute("data-camera-scale"));
    await page.locator("[data-simple-geometry-action='zoom-in']").click();
    await page.waitForFunction((before) => Number(document.querySelector("#geometry-explorer")?.dataset.cameraScale) > before, localCameraScale);
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-geometric-zoom-applied"), "false");
    const fade = page.locator("[data-local-comparison-opacity]");
    await fade.focus(); await page.keyboard.press("End");
    assert.equal(await fade.inputValue(), "100");
    await page.keyboard.press("Home");
    assert.equal(await fade.inputValue(), "0");
    await fade.evaluate((input) => { input.value = "50"; input.dispatchEvent(new Event("input", { bubbles: true })); });
    await page.locator("[data-simple-geometry-action='comparison']").focus(); await page.keyboard.press("Enter");
    await page.waitForFunction(() => window.GeometryExplorer.localComparison === "raw_projected_patches");
    await page.locator("[data-simple-geometry-action='comparison']").focus(); await page.keyboard.press("Enter");
    await page.waitForFunction(() => window.GeometryExplorer.localComparison === "normalized_log_comparison" && document.querySelector("#geometry-explorer")?.dataset.localChartNormalization === "true");
    assert.deepEqual(await page.evaluate(() => ({ parentIds: window.GeometryExplorer.currentRecord.parentPoints.map((point) => point.id), childIds: window.GeometryExplorer.currentRecord.children.map((point) => point.id), roots: window.GeometryExplorer.currentRecord.rootMultiIndex })), comparisonBefore, "comparison display controls must not alter source pairing");
    assert.deepEqual(await page.evaluate(() => ({ selected: window.GeometryExplorer.selectedSliceVertex.id, sourceIds: window.GeometryExplorer.sliceRecord.sourceRecords.map((point) => point.id) })), fermatSourceBefore, "camera and comparison controls must not alter the Fermat source records");
    await page.locator("#geometry-explorer").screenshot({ path: path.join(root, "geometry-explorer-fermat-browser.png") });
    await page.locator("[data-simple-geometry-action='surface']").click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.mode === "slice");
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator("#geometry-explorer").scrollIntoViewIfNeeded();
    for (const selector of ["[data-simple-geometry-action='fermat']", "[data-slice-preset]", "[data-simple-geometry-action='explore']", "#geometry-explorer canvas"]) {
      const box = await page.locator(selector).boundingBox();
      assert.ok(box && box.x >= 0 && box.x + box.width <= 390, selector + " must fit the 390 px layout");
    }
    await page.locator("#geometry-explorer").screenshot({ path: path.join(root, "geometry-explorer-fermat-mobile.png") });
    await page.setViewportSize({ width: 1440, height: 1000 });
    const zero = await page.evaluate(() => {
      const record = window.GeometryExplorer.currentRecord;
      for (let branch = 0; branch < record.branches.length; branch += 1) {
        const vertexIndex = record.branches[branch].records.findIndex((point) => point.coordinates.some((z) => Math.hypot(z.re, z.im) < 1e-10));
        if (vertexIndex >= 0) return { branch, vertexIndex, id: record.branches[branch].records[vertexIndex].id };
      }
      return null;
    });
    assert.ok(zero);
    await page.evaluate((selection) => { window.GeometryExplorer.selectedSliceVertex = selection; }, zero);
    await page.locator("[data-simple-geometry-action='explore']").click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "refused" && /ineligible/.test(document.querySelector("[data-simple-geometry-caption]")?.textContent || ""));
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-point-count"), "0");
    assert.equal(await page.locator("#geometry-explorer canvas").isVisible(), true, "a refused source point keeps the prior valid slice visible");
    await page.locator("[data-simple-geometry-action='surface']").click();
    await page.locator("[data-slice-preset]").selectOption("laurent-open-wings");
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.formulaId === "W_kappa_torus4_v1" && document.querySelector("#geometry-explorer")?.dataset.mode === "slice");
    assert.equal(await page.evaluate(() => window.GeometryExplorer.localComparison), "raw_projected_patches", "a slice change clears stale comparisons without generating a pullback");
    await page.locator("[data-geometry-parameter='lambda']").evaluate((input) => { input.max = "4"; input.value = "4"; input.dispatchEvent(new Event("input", { bubbles: true })); });
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "refused" && /Slice change refused/.test(document.querySelector("[data-simple-geometry-error]")?.textContent || ""));
    assert.equal(await page.locator("#geometry-explorer canvas").isVisible(), true, "an invalid parameter keeps the previous valid slice visible");
    await page.locator("[data-geometry-parameter='lambda']").evaluate((input) => { input.value = "1"; input.dispatchEvent(new Event("input", { bubbles: true })); });
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready");
    await page.locator('[data-ui-mode="expert"]').click();
    await page.locator("#expert-workbench").waitFor({ state: "visible" });
    await page.waitForFunction(() => ["ready", "error"].includes(document.querySelector("#geometry-explorer")?.dataset.state), null, { timeout: 20000 });
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-state"), "ready", "GPU fallback must reach a visible ready state");
    assert.equal(await page.locator("#geometry-explorer canvas").isVisible(), true);
    assert.match(await page.locator("[data-geometry-detail]").innerText(), /Declared parameter subfamily/);
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-discriminant"), "regular");
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-complete-x0-rendered"), "false");
    for (const mode of ["phase", "cloud", "slice"]) {
      await page.locator("[data-geometry-mode='" + mode + "']").click();
      await page.waitForFunction((wanted) => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.mode === wanted, mode);
    }
    await page.locator("[data-geometry-parameter='lambda']").evaluate((input) => { input.value = "2"; input.dispatchEvent(new Event("input", { bubbles: true })); });
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("[data-geometry-detail]")?.textContent.includes("λ=2"));
    await page.locator("[data-geometry-action='singular']").click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.discriminant === "singular");
    assert.match(await page.locator("[data-geometry-discriminant]").innerText(), /not a renderer proof/);
    await page.locator("[data-geometry-parameter='kappa']").evaluate((input) => { input.value = "0.010240000000001"; input.dispatchEvent(new Event("input", { bubbles: true })); });
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.discriminant === "numerical-inconclusive");
    for (const name of ["lambda", "kappa"]) await page.locator("[data-geometry-parameter='" + name + "']").evaluate((input) => { input.value = "1"; input.dispatchEvent(new Event("input", { bubbles: true })); });
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.discriminant === "regular");
    await page.locator("[data-geometry-mode='pullback']").click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.pointCount === "8192");
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-complete-global-xn-rendered"), "false");
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-complete-fiber-over-finite-scope"), "true");
    await page.locator("[data-geometry-parameter='D']").evaluate((input) => { input.value = "3"; input.dispatchEvent(new Event("input", { bubbles: true })); });
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "refused");
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-required-point-count"), "41472");
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-point-count"), "0");
    await page.locator("[data-geometry-scope]").selectOption("one-ancestor");
    await page.locator("[data-geometry-ancestor]").selectOption("1");
    await page.locator("[data-geometry-parameter='D']").evaluate((input) => { input.value = "2"; input.dispatchEvent(new Event("input", { bubbles: true })); });
    await page.locator("[data-geometry-parameter='depth']").evaluate((input) => { input.value = "2"; input.dispatchEvent(new Event("input", { bubbles: true })); });
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.pointCount === "256");
    const firstPoint = await page.evaluate(() => window.GeometryExplorer.currentRecord.points[0].id);
    assert.match(firstPoint, /^x0-p/);
    await page.locator("[data-geometry-point-inspector] summary").click();
    await page.locator("[data-geometry-point-index]").fill("5");
    assert.match(await page.locator("[data-geometry-point-evidence]").innerText(), /root indices .*parent power residual .*inherited W-membership residual/);
    const beforeFitFactor = Number(await page.locator("#geometry-explorer").getAttribute("data-display-normalization-factor"));
    await page.locator("[data-geometry-local-fit]").check();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.displayNormalization === "ancestor_recenter_fit");
    assert.equal(await page.evaluate(() => window.GeometryExplorer.currentRecord.points[0].id), firstPoint);
    assert.ok(Number.isFinite(Number(await page.locator("#geometry-explorer").getAttribute("data-display-normalization-factor"))));
    assert.ok(beforeFitFactor > 0);
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-geometric-zoom-applied"), "false");
    const beforeCameraScale = Number(await page.locator("#geometry-explorer").getAttribute("data-camera-scale"));
    await page.locator("#geometry-explorer canvas").hover();
    await page.mouse.wheel(0, -400);
    await page.waitForFunction((before) => Number(document.querySelector("#geometry-explorer")?.dataset.cameraScale) > before, beforeCameraScale);
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-camera-scale-semantic"), "visual_camera_dolly");
    assert.equal(await page.locator("#geometry-explorer").getAttribute("data-geometric-zoom-applied"), "false");
    await page.reload({ waitUntil: "networkidle" });
    await page.locator('[data-ui-mode="expert"]').click();
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready");
    await page.locator("[data-geometry-mode='pullback']").click();
    await page.locator("[data-geometry-scope]").selectOption("one-ancestor");
    await page.locator("[data-geometry-ancestor]").selectOption("1");
    await page.locator("[data-geometry-parameter='depth']").evaluate((input) => { input.value = "2"; input.dispatchEvent(new Event("input", { bubbles: true })); });
    await page.waitForFunction(() => document.querySelector("#geometry-explorer")?.dataset.state === "ready" && document.querySelector("#geometry-explorer")?.dataset.pointCount === "256");
    assert.equal(await page.evaluate(() => window.GeometryExplorer.currentRecord.points[0].id), firstPoint, "finite pullback point identity must replay after reload");
    const png = path.join(root, "geometry-explorer-browser.png");
    await page.locator("#geometry-explorer").screenshot({ path: png });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator("#geometry-explorer").scrollIntoViewIfNeeded();
    assert.equal(await page.locator("#geometry-explorer canvas").isVisible(), true, "mobile layout must retain the render surface");
    assert.ok(await page.locator("#geometry-explorer").boundingBox());
    await page.locator("#geometry-explorer").screenshot({ path: path.join(root, "geometry-explorer-mobile.png") });
    assert.deepEqual(errors, []);
    console.log("Geometry exploration engine browser verification: passed");
    console.log("Screenshot: " + png);
  } finally {
    await browser.close();
    await new Promise((resolve) => instance.close(resolve));
  }
})().catch((error) => { console.error(error); process.exitCode = 1; });
