import SelfSimilarCY.CoordinatePowerIteration

namespace SelfSimilarCY

/--
The abstract pullback tower generated by the canonical coordinate-power map.

`pullbackTower D X n` records only repeated set-theoretic preimage under
`coordinatePower D`. It introduces no Calabi--Yau geometry, degree theorem,
sheet model, covering-space structure, or metric claim.
-/
def pullbackTower (D : ℕ) (X : Set Point4) : ℕ → Set Point4
  | 0 => X
  | Nat.succ n => coordinatePower D ⁻¹' pullbackTower D X n

@[simp]
theorem pullbackTower_zero (D : ℕ) (X : Set Point4) :
    pullbackTower D X 0 = X := rfl

@[simp]
theorem pullbackTower_succ (D : ℕ) (X : Set Point4) (n : ℕ) :
    pullbackTower D X n.succ = coordinatePower D ⁻¹' pullbackTower D X n := rfl

/--
The recursive pullback tower is exactly the preimage of `X` under the
`n`-fold function iterate of `coordinatePower D`.
-/
theorem pullbackTower_eq_iterate_preimage
    (D : ℕ) (X : Set Point4) (n : ℕ) :
    pullbackTower D X n = ((coordinatePower D)^[n]) ⁻¹' X := by
  induction n with
  | zero =>
      rfl
  | succ n ih =>
      change coordinatePower D ⁻¹' pullbackTower D X n =
        ((coordinatePower D)^[n.succ]) ⁻¹' X
      rw [ih, Function.iterate_succ, Set.preimage_comp]

/--
Using the sealed F03 iteration theorem, depth `n` is equivalently the preimage
under the single coordinate-power map with exponent `D ^ n`.
-/
theorem pullbackTower_eq_coordinatePower_preimage
    (D : ℕ) (X : Set Point4) (n : ℕ) :
    pullbackTower D X n = (coordinatePower (D ^ n)) ⁻¹' X := by
  rw [pullbackTower_eq_iterate_preimage, coordinatePower_iterate]

end SelfSimilarCY
